### ISSUE TITLE
Image are not being queried

### ISSUE THREAD

**Issue by aleku399** [aleku399/gatsby-starter-netlify-cms#1]
the frontmatter field for the image is null is cureently being queried for the about page in about/index.md

**Comment by aleku399** [comment]
you can find the query in about.js

**Comment by epicallan** [comment]
there is no `about.js` page in the project. Can you update master branch

**Comment by aleku399** [comment]
its about-page.js

**Comment by aleku399** [comment]
what do u mean by update master branch

**Comment by epicallan** [comment]
> what do u mean by update master branch

I thought you hadn't updated master branch as the reason for the missing about.js file

> the frontmatter field for the image is null is for about page in about/index.md

Isn't that because you are not adding it to the front matter in `about/index.md`

I don't see an image value in your frontmatter for `about/index.md`.  Also, `product-page.js` is an excellent example of how to work with images, look through it.

**Comment by aleku399** [comment]
okk
